[platformio]
default_envs = esp32

[env]
build_flags = -Wall -Wextra -fno-exceptions -O0 -fno-rtti -fno-strict-aliasing -fno-fast-math

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
    adafruit/Adafruit LSM9DS1 Library@^2.2.1
    adafruit/Adafruit VEML7700 Library@^2.1.6
    mikalhart/TinyGPSPlus@^1.1.0
build_unflags = -std=gnu++11 -std=c++11
build_flags = ${env.build_flags} -D CONFIG_FREERTOS_NUMBER_OF_CORES=2 -std=gnu++17
    
lib_ldf_mode = deep+
test_framework = unity

[env:desktop]
platform = native
build_flags = ${env.build_flags} -std=gnu++23 -Werror
test_framework = unity